config/routes.rb
Css3KeyFrameAnimation::Application.routes.draw do
  resources :csses 
  
  root :to =>  'csses#index'

end

app/models/css.rb
class Css < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/csses_controller.rb
class CssesController < ApplicationController
  # GET /csses
  # GET /csses.xml
  def index
    @csses = Css.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @csses }
    end
  end

  # GET /csses/1
  # GET /csses/1.xml
  def show
    @css = Css.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @css }
    end
  end

  # GET /csses/new
  # GET /csses/new.xml
  def new
    @css = Css.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @css }
    end
  end

  # GET /csses/1/edit
  def edit
    @css = Css.find(params[:id])
  end

  # POST /csses
  # POST /csses.xml
  def create
    @css = Css.new(params[:css])

    respond_to do |format|
      if @css.save
        format.html { redirect_to(@css, :notice => 'Css was successfully created.') }
        format.xml  { render :xml => @css, :status => :created, :location => @css }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @css.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /csses/1
  # PUT /csses/1.xml
  def update
    @css = Css.find(params[:id])

    respond_to do |format|
      if @css.update_attributes(params[:css])
        format.html { redirect_to(@css, :notice => 'Css was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @css.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /csses/1
  # DELETE /csses/1.xml
  def destroy
    @css = Css.find(params[:id])
    @css.destroy

    respond_to do |format|
      format.html { redirect_to(csses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cs_ses_helper.rb
module CsSesHelper
end

app/views/csses/_form.html.erb
<%= form_for(@css) do |f| %>
  <% if @css.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@css.errors.count, "error") %> prohibited this css from being saved:</h2>

      <ul>
      <% @css.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/csses/edit.html.erb
<h1>Editing css</h1>

<%= render 'form' %>

<%= link_to 'Show', @css %> |
<%= link_to 'Back', csses_path %>

app/views/csses/index.html.erb
<h1>CSS Keyframe animation</h1> 

<div class = "box1"></div>
<div class = "box2"></div>
<div class = "box3"></div>  
<div class = "box4"></div> 
 

app/views/csses/new.html.erb
<h1>New css</h1>

<%= render 'form' %>

<%= link_to 'Back', csses_path %>

app/views/csses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @css.title %>
</p>


<%= link_to 'Edit', edit_css_path(@css) %> |
<%= link_to 'Back', csses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Css3KeyFrameAnimation</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>